CREATE TABLE rd_article (
    id INT AUTO_INCREMENT PRIMARY KEY,
    article_name VARCHAR(255) UNIQUE,
    url VARCHAR(255) UNIQUE,
    tag VARCHAR(255),
    create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;